import React from "react";

export const strings = {
    MENU_ITEM_DASHBOARD: 'Dashboard',
    MENU_ITEM_CUSTOMERS: 'Customers',
    MENU_ITEM_FEEDBACKS: 'Feedbacks',
    MENU_ITEM_LICENSES: 'Licenses',
    MENU_ITEM_STATISTICS: 'Statistics',

    PAGE_NOT_FOUND: 'Not found',

    CHART_HITS_TITLE: 'Summary of hits',
    CHART_HITS_YAXIS_TITLE: 'Count',
    CHART_DOMAINS_TITLE: 'Summary of domains',
    CHART_DOMAINS_YAXIS_TITLE: 'Count',
    CHART_FEEDBACKS_TITLE: 'Summary of feedbacks',
    CHART_FEEDBACKS_TITLE_YEAR: 'Year summary of feedbacks',
    CHART_FEEDBACKS_YAXIS_TITLE: 'Count',
    CHART_DEVICE_TITLE: 'Host id: ',
    CHART_DEVICE_YAXIS_TITLE: 'Months',
    CHART_DEVICE_SERIES_NAME: 'Count',
    CHART_KERNUN_VERSION_SERIES_NAME: 'Count',
    CHART_KERNUN_VARIANTS_TITLE: 'Kernun variants',
    CHART_KERNUN_VARIANTS_SERIES_NAME: 'Count',
    CHART_KCW_AUTH_TITLE: 'KCW Auth',
    CHART_KCW_AUTH_SERIES_NAME: 'Count',
    CHART_KCW_FUNCTIONS_TITLE: 'KCW functions',

    PERIOD_TODAY: 'Today',
    PERIOD_WEEK: 'Week',
    PERIOD_MONTH: 'Month',
    PERIOD_YEAR: 'Year',

    TOOLTIP_ACTIVE_FB : 'Active with today\'s feedback',
    TOOLTIP_ACTIVE_NO_FB: 'Active with no today\'s feedback',
    TOOLTIP_INACTIVE_FB: 'Inactive with today\'s feedback',
    TOOLTIP_INACTIVE_NO_FB: 'Inactive with no today\'s feedback',
    TOOLTIP_OTHER: 'Other',
    TOOLTIP_FB : 'There was a feedback today',
    TOOLTIP_NO_FB : 'There was no feedback today',
    TOOLTIP_REBOOT : 'Reboot',
    TOOLTIP_EXPIRATION: 'License expiration',
    TOOLTIP_PANICS: 'Nonzero n_panics',
    TOOLTIP_ABORTS: 'Nonzero n_aborts',
    TOOLTIP_CORE_DUMPS: 'Nonempty core_dumps',
    TOOLTIP_HIGH_REPORTER_USERS: 'devcount greater than reporter_users',
    TOOLTIP_HIGH_REPORTER_CLIENTS: 'devcount greater than reporter_clients',

    HEADER_ACTIVE_CUSTOMERS: 'Active customers (license upgrade in the future)',
    HEADER_INACTIVE_CUSTOMERS: 'Inactive customers',
    HEADER_LEGEND_STATUS: 'Legend for status',
    HEADER_LEGEND_CUSTOMER : 'Legend for customer',
    HEADER_LICENSE_SERIAL: 'Serial number: ',
    HEADER_FB_LIST: 'Feedback list',

    TABLE_COLUMN_CUSTOMER: 'Customer',
    TABLE_COLUMN_DETERMINED_CUSTOMER: 'Determined customer',
    TABLE_COLUMN_FA_ID: 'Fa_id',
    TABLE_COLUMN_UPLOAD_START: 'Upload_start',
    TABLE_COLUMN_EXPIRATION: 'Expiration',
    TABLE_COLUMN_UPGRADE: 'Upgrade',
    TABLE_COLUMN_IDENT: 'Ident',
    TABLE_COLUMN_SERIAL: 'Serial',
    TABLE_COLUMN_HOSTNAME: 'Hostname',
    TABLE_COLUMN_FB_HOSTNAME: 'Feedback_hostname',
    TABLE_COLUMN_STATUS: 'Status',
    TABLE_COLUMN_SALE_TYPE: 'Sale',
    TABLE_COLUMN_LICENSE_TYPE: 'License',
    TABLE_COLUMN_KERNUN_VARIANT: 'Kernun variant',
    TABLE_COLUMN_KERNUN_VERSION: 'Kernun version',

    FB_DETAIL_FA_ID: 'fa_id',
    FB_DETAIL_DETERMINED_CUSTOMER: 'determined_customer',
    FB_DETAIL_DOMAINS: 'domains',
    FB_DETAIL_FB_HOSTNAME: 'feedback_hostname',
    FB_DETAIL_FB_IP: 'feedback_ip',
    FB_DETAIL_FN: 'fn',
    FB_DETAIL_HITS: 'hits',
    FB_DETAIL_SIZE: 'size',
    FB_DETAIL_PROCESSED: 'processed',
    FB_DETAIL_UPLOAD_START: 'upload_start',
    FB_DETAIL_UPLOAD_FINISH: 'upload_finish',
    FB_DETAIL_IDENT: 'ident',
    FB_DETAIL_CUSTOMER: 'customer',
    FB_DETAIL_SERIAL: 'serial',
    FB_DETAIL_DEVCOUNT: 'devcount',
    FB_DETAIL_HW: 'hw',
    FB_DETAIL_EXPIRATION: 'expiration',
    FB_DETAIL_UPGRADE: 'upgrade',
    FB_DETAIL_GROUP_TYPE: 'group_type',
    FB_DETAIL_CPU_MODEL: 'cpu_model',
    FB_DETAIL_CPU_NUMBER: 'cpu_number',
    FB_DETAIL_DMI_PRODUCT: 'dmi_product',
    FB_DETAIL_HOSTID: 'hostid',
    FB_DETAIL_HOSTNAME: 'hostname',
    FB_DETAIL_KERNUN_VARIANT: 'kernun_variant',
    FB_DETAIL_KERNUN_VERSION: 'kernun_version',
    FB_DETAIL_VM_GUEST: 'vm_guest',
    FB_DETAIL_UPTIME: 'uptime',
    FB_DETAIL_DISK_SPACE: 'disk_space',
    FB_DETAIL_SYSTEM_TABLE: 'system_table',
    FB_DETAIL_VM_STAT: 'vm_stat',
    FB_DETAIL_CORE_DUMPS: 'core_dumps',
    FB_DETAIL_RRD_PROXIES: 'rrd_proxies',
    FB_DETAIL_N_PANICS: 'n_panics',
    FB_DETAIL_N_ABORTS: 'n_aborts',
    FB_DETAIL_REP_MIN_TIME: 'reporter_min_time',
    FB_DETAIL_REP_MAX_TIME: 'reporter_max_time',
    FB_DETAIL_REP_USERS: 'reporter_users',
    FB_DETAIL_REP_CLIENTS: 'reporter_clients',
    FB_DETAIL_CW_CATEGORIZED: 'reporter_cw_categorized',
    FB_DETAIL_CW_TOTAL: 'reporter_cw_total',
    FB_DETAIL_WEB_CATEGORIZED: 'reporter_web_categorized',
    FB_DETAIL_WEB_TOTAL: 'reporter_web_total',

    KCW_FUNC_DEPLOYMENT: 'cw_deployment',
    KCW_FUNC_DHCP_CLIENT: 'cw_dhcp_client',
    KCW_FUNC_NETIF_DEVICES: 'cw_netif_devices',
    KCW_FUNC_TIME_ZONE: 'cw_time_zone',
    KCW_FUNC_SSHD_ENABLED: 'cw_sshd_enabled',
    KCW_FUNC_SSHD_KERNUN: 'cw_sshd_kernun',
    KCW_FUNC_AUTO_UPDATE: 'cw_auto_update',
    KCW_FUNC_LOG_ROTATION: 'cw_log_rotation',
    KCW_FUNC_PROXY_LANG: 'cw_proxy_lang',
    KCW_FUNC_HAND_OFF: 'cw_hand_off',
    KCW_FUNC_DHCP_SERVER: 'cw_dhcp_server',
    KCW_FUNC_HTTPS_INSP: 'cw_https_insp',
    KCW_FUNC_AUTH: 'cw_auth',
    KCW_FUNC_ANTIVIRUS: 'cw_antivirus',
};